steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/hirooka-pro/dqwui/dqwui', '.']

images:
  - 'asia-northeast1-docker.pkg.dev/hirooka-pro/dqwui/dqwui'
