steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/hirooka-pro/dqwui/dqwui', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dqwapi'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/hirooka-pro/dqwui/dqwui'
      - '--region'
      - 'asia-northeast1'
images:
  - 'asia-northeast1-docker.pkg.dev/hirooka-pro/dqwui/dqwui'
